dist: bionic
language: r
r:
  - release

before_install:
  - sudo apt-get install r-cran-tkrplot bwidget

services:
  - xvfb

repos:
  CRAN: https://cloud.r-project.org

r_packages:
  - devtools
  - roxygen2
  - knitr
  - rmarkdown

cache: packages
warnings_are_errors: false
r_check_args: "--no-vignettes"
r_build_args: "--as-cran --no-build-vignettes"
